info:
  app:
    name: MyApplication
    description: This is my Spring Boot application.
    version: 1.0.0
  build:
    artifact: my-app
    name: My Application
    time: 2023-07-17T12:00:00Z
    version: 1.0.0

server:
  port: 8002

spring:
  application:
    name: product-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: health,info,env,metrics
  endpoint:
    health:
      show-details: always
logging:
  level:
    com.netflix.eureka: WARN
    com.netflix.discovery: WARN
