server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/your-repo/config-repo
          default-label: master

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
